In [1]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [21]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,8,7,5,3]
arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 5 3]]


In [22]:
arr.shape

(3, 5)

In [24]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 5, 3]])

In [25]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [23]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 5, 3]])

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [13]:
arr[3]

4