In [44]:
import numpy as np

In [45]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [46]:
print(arr)

[1 2 3 4 5]


In [47]:
arr.shape

(5,)

In [48]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,8,7,5,3]
arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 5 3]]


In [49]:
arr.shape

(3, 5)

In [50]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 5, 3]])

In [51]:
arr[2:5,1:2]

array([[8]])

In [52]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [53]:
arr[0:2,2:3]

array([[3],
       [4]])

In [54]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 5, 3]])

In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [56]:
arr[3]

4

In [57]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,8,7,5,3]
arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 8 7 5 3]]


In [66]:
arr[1:,2:4,]

array([[4, 5],
       [7, 5]])