In [1]:
import numpy as np


In [3]:
df =  np.array([1,2,3,4,5,])
df

array([1, 2, 3, 4, 5])

In [4]:
df.ndim

1

In [8]:
df = np.array([[1,2,3],[4,5,6],[7,8,9]])
df

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
df.ndim

2

In [10]:
df.shape

(3, 3)

In [11]:
x = np.arange(-10,10,0.5)

In [12]:
x

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [14]:
x.shape

(40,)

In [22]:
x = np.linspace(1,100,5,endpoint=False)
x

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [25]:
a = np.random.rand(8,8)
print(a)

[[[0.79941847 0.50962748 0.51217709 0.54870467 0.77219631 0.41973861
   0.23651755 0.78634643]
  [0.7478154  0.62692    0.94089685 0.3533674  0.20436011 0.83806635
   0.59908278 0.37796063]
  [0.80383892 0.85089326 0.08266371 0.44232763 0.51444086 0.22608948
   0.50600918 0.62742099]
  [0.2286197  0.57946493 0.66226218 0.68277373 0.95395328 0.05559482
   0.81312957 0.17059413]
  [0.46506405 0.20407913 0.62128565 0.9062445  0.99652425 0.92596969
   0.99045025 0.5960466 ]
  [0.23387375 0.77880932 0.6006768  0.74742199 0.74122247 0.9193468
   0.01121227 0.50452471]
  [0.91501338 0.30774233 0.52034865 0.29149945 0.84114131 0.13334032
   0.05869183 0.97883311]
  [0.38675976 0.90439153 0.98791296 0.61697539 0.40577861 0.42747154
   0.39196034 0.51454049]]

 [[0.60456381 0.75455646 0.34853947 0.02446259 0.76431235 0.60117785
   0.72202415 0.22556995]
  [0.66230185 0.32340605 0.92144134 0.8331198  0.25513158 0.19646411
   0.33349152 0.35018293]
  [0.28554843 0.42340371 0.45433359 0.88103375 0.

In [26]:
c = np.random.randint(0,101,(3,3))
print(c)

[[17 42 60]
 [63 99 15]
 [ 9  9 17]]


In [28]:
d = np.random.choice(['😂','😀','🤣'],(3,3))
print(d)

[['🤣' '😂' '🤣']
 ['😂' '😂' '😀']
 ['🤣' '😀' '😀']]


In [30]:
o = np.ones((3,3),dtype = int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [31]:
e = np.eye(6,dtype = int)
print(e)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [35]:
o = np.diag(df)
print(o)

[1 5 9]


In [38]:
c

array([[17, 42, 60],
       [63, 99, 15],
       [ 9,  9, 17]])

In [37]:
c.transpose()

array([[17, 63,  9],
       [42, 99,  9],
       [60, 15, 17]])

In [39]:
c.size

9

In [40]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,9],[6,5]])
print(x+y)

[[ 9 18]
 [12 14]]


In [41]:
x + 5

array([[11, 14],
       [11, 14]])

In [42]:
x.dot(y)

array([[72, 99],
       [72, 99]])

In [43]:
np.cross(x,y)

array([ 27, -24])

In [44]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [45]:
r = np.random.randint(-101,101,(5,5))
r

array([[  56,  -87,  -99,   -9,  -30],
       [ -96,    4,   38,   28, -100],
       [ -92,   11,   99,   93,  -97],
       [  76,   33,   46,    8,  -55],
       [ -73,  -20,  -10,  -88,  -89]])

In [46]:
r.max(),r.min()

(99, -100)

In [47]:
print(r.sum(),r.mean(),r.std(),r.var(),r.prod())

-453 -18.12 64.72917116725658 4189.865600000001 1073741824
