In [1]:
import numpy as np


In [2]:
df =  np.array([1,2,3,4,5,])
df

array([1, 2, 3, 4, 5])

In [3]:
df.ndim

1

In [4]:
df = np.array([[1,2,3],[4,5,6],[7,8,9]])
df

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
df.ndim

2

In [6]:
df.shape

(3, 3)

In [7]:
x = np.arange(-10,10,0.5)

In [8]:
x

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [9]:
x.shape

(40,)

In [10]:
x = np.linspace(1,100,5,endpoint=False)
x

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [11]:
a = np.random.rand(8,8)
print(a)

[[0.57551539 0.98058442 0.80624859 0.41913588 0.70097812 0.20854714
  0.93757072 0.58390879]
 [0.53387882 0.60953772 0.37479636 0.00136857 0.32497174 0.43593786
  0.55424452 0.17293365]
 [0.64491984 0.73347147 0.7893291  0.59268909 0.47435169 0.02490327
  0.66515179 0.3210612 ]
 [0.13505361 0.67286535 0.79269086 0.88333781 0.08329895 0.26902835
  0.18838912 0.98613928]
 [0.1262471  0.54531727 0.77595349 0.69070989 0.27522584 0.06763555
  0.99187527 0.69558951]
 [0.67602158 0.84625414 0.26767766 0.89920128 0.0157883  0.40109828
  0.6079459  0.87207727]
 [0.25194013 0.96887261 0.11474741 0.56050181 0.97078311 0.37489481
  0.13679245 0.5879964 ]
 [0.4430519  0.03750569 0.12075843 0.84751149 0.195474   0.0646989
  0.41270879 0.9067335 ]]


In [12]:
c = np.random.randint(0,101,(3,3))
print(c)

[[11 30 47]
 [ 8 46 14]
 [28 16  6]]


In [13]:
d = np.random.choice(['😂','😀','🤣'],(3,3))
print(d)

[['🤣' '😂' '😂']
 ['😀' '😂' '🤣']
 ['😂' '😀' '😀']]


In [14]:
o = np.ones((3,3),dtype = int)
print(o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
e = np.eye(6,dtype = int)
print(e)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [16]:
o = np.diag(df)
print(o)

[1 5 9]


In [17]:
c

array([[11, 30, 47],
       [ 8, 46, 14],
       [28, 16,  6]])

In [18]:
c.transpose()

array([[11,  8, 28],
       [30, 46, 16],
       [47, 14,  6]])

In [19]:
c.size

9

In [20]:
x = np.array([[6,9],[6,9]])
y = np.array([[3,9],[6,5]])
print(x+y)

[[ 9 18]
 [12 14]]


In [21]:
x + 5

array([[11, 14],
       [11, 14]])

In [22]:
x.dot(y)

array([[72, 99],
       [72, 99]])

In [23]:
np.cross(x,y)

array([ 27, -24])

In [24]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [25]:
r = np.random.randint(-101,101,(5,5))
r

array([[  0, -69, -73, -27,  63],
       [ 11, -20,  76, -32, -87],
       [ 18,   3, -44, -14, -54],
       [ 78,  36,  35,  38, -11],
       [ 66,  20,  47, -72,  99]])

In [26]:
r.max(),r.min()

(99, -87)

In [27]:
print(r.sum(),r.mean(),r.std(),r.var(),r.prod())

87 3.48 51.72088166301886 2675.0496000000003 0


In [28]:
x = np.random.randint(0,101,(3,3))
y = np.random.randint(0,101,(3,3))
print(x,y,sep = '\n\n')

[[76 74  1]
 [69 15 38]
 [19 61 21]]

[[68 47 72]
 [63 39 53]
 [31 14  5]]


In [29]:
x@y

array([[9861, 6472, 9399],
       [6815, 4360, 5953],
       [5786, 3566, 4706]])

# numpy slicing (in 2D array)
arr[row_start:row_end,col_start:col_end]

In [31]:
a = np.random.randint(10,100,(10,5))
a

array([[91, 10, 85, 13, 34],
       [78, 67, 82, 68, 73],
       [90, 97, 74, 21, 61],
       [38, 40, 26, 16, 80],
       [26, 84, 70, 48, 47],
       [98, 11, 62, 92, 15],
       [45, 34, 32, 36, 62],
       [70, 96, 24, 41, 42],
       [52, 33, 55, 74, 79],
       [54, 66, 41, 40, 47]])

In [32]:
#top 5 rows
print(a[:5])
# last 3 rows
print(a[-3:])


[[91 10 85 13 34]
 [78 67 82 68 73]
 [90 97 74 21 61]
 [38 40 26 16 80]
 [26 84 70 48 47]]
[[70 96 24 41 42]
 [52 33 55 74 79]
 [54 66 41 40 47]]


In [34]:
print(a[:,1])
print(a[:,[0,2,4]])
print(a[:5,:3])

[10 67 97 40 84 11 34 96 33 66]
[[91 85 34]
 [78 82 73]
 [90 74 61]
 [38 26 80]
 [26 70 47]
 [98 62 15]
 [45 32 62]
 [70 24 42]
 [52 55 79]
 [54 41 47]]
[[91 10 85]
 [78 67 82]
 [90 97 74]
 [38 40 26]
 [26 84 70]]
